Add slurm guide
TOAST-DOCS/Compute-Image-Builder pull request #34
Opened 2022-01-05 02:10 UTC by tskim-nhn

2022-01-05 07:02 UTC, 5bpa requested changes

2022-01-05 07:02 UTC, 5bpa commented on ko/component-guide.md
> +### Slurm 실행
실행하는 방법을 꼭 써줘야 할까 싶긴 하네요.
위에 설정이 제대로 되었을때나 실행이 될텐데요. 
우리가 설정을 꼼꼼하게 다 알려주는 건 아닌 상황이라서요. 

실행하는 방법은 slurm 사이트를 참고하라고 해 주는 정도로 마무리하면 어떨까 싶기도 합니다.

2022-01-05 09:03 UTC, tskim-nhn commented on ko/component-guide.md
> +
Installation guide와 어디까지 진행하는지 추가하였습니다.

2022-01-05 09:12 UTC, tskim-nhn commented on ko/component-guide.md
> +### Slurm 실행
실행 방법이 없으면, 가이드가 설정 안내만 도와주고 중간에 끝나는 느낌이 있어 보입니다.
실행 방법이 나와있는 installation guide 사이트는 8번까지는 저희가 해주는 작업을 알려주고, 10-11번에 실행방법이 표시 되어 있어 직접적으로 실행 방법을 전달하는 것이 애매해보여서요. (심지어 start daemons 라고만 나와있습니다.)

차라리 (1)설정은 Configuration Tool을 통해 작성한 후 실행하라는 것과 (2)실행에 문제가 있을 경우 로그 확인할 수 있는 방법을 주고 설정값 혹은 installation guide를 확인하라는 문구를 추가하면 어떨까요?

2022-01-07 06:52 UTC, 5bpa commented on ko/component-guide.md
> +Image Builder는 Slurm 작동을 위한 Munge 설치 및 설정, 그리고 Slurm 설치까지 진행합니다. 실행을 위한 자세한 방법은 [Slurm Installation Guide](https://slurm.schedmd.com/quickstart_admin.html)를 참고하세요.
"Image builder 는" 주어가 좀 어색하네요. slurm 스크립트가 주어가 되는게 더 정확해 보입니다.

2022-01-07 06:52 UTC, 5bpa commented on ko/component-guide.md
> +### Slurm 실행
Slurm 이 우리가 만든 서비스라면 당연히 실행까지 설명하는게 맞아 보입니다만,
우리가 하는 건 패키지 설치와 약간의 설정까지이므로, 
저희 가이드를 보고 실행까지 진행할 수는 없지요.

사용자가 설정을 잘 하고 실행까지 가야 하는데요.
slurm 사이트에서 설정까지 하고 나면 실행하는 가이드도 나오니까요.
저희는 그 링크를 주고 마무리하는게 좋겠습니다. 

L673에서  "Slurm 설정과 실행" 으로 퉁치고요.

2022-01-07 06:59 UTC, arzhna commented on ko/component-guide.md
> +Image Builder는 Slurm 작동을 위한 Munge 설치 및 설정, 그리고 Slurm 설치까지 진행합니다. 실행을 위한 자세한 방법은 [Slurm Installation Guide](https://slurm.schedmd.com/quickstart_admin.html)를 참고하세요.
스크립트는 사용하는 용어가 아닙니다. 설치 구성 요소가 맞습니다.
> Slurm 설치 구성 요소는 Munge 설치 및 설정, 그리고 Slurm 설치를 진행합니다.

2022-01-07 08:59 UTC, tskim-nhn commented
@5bpa @arzhna 

말씀하신대로 가이드를 최소화했습니다. 확인 한 번 부탁드립니다.

2022-01-11 06:33 UTC, 5bpa approved these changes

2022-01-12 01:09 UTC, youngkyungyu commented on ko/component-guide.md
> +Image Builder 서비스를 통한 Slurm의 환경설정은 사용자가 직접 하여야 합니다. 아래는 설정과 실행에 대한 간단 설명입니다. 아래 명령어는 모두 root 권한으로 실행하여야 합니다.
=> Image Builder 서비스를 통한 Slurm의 환경 설정은 사용자가 직접해야 합니다.

2022-01-12 01:10 UTC, youngkyungyu commented on ko/component-guide.md
> +아래 명령어를 통해 slurm daemon을 실행시킬 수 있습니다.
아래 명령어를 사용해 slurm daemon을 실행할 수 있습니다.

2022-01-12 01:12 UTC, youngkyungyu commented on ko/component-guide.md
> +아래 명령어는 모두 root 권한으로 실행하여야 합니다.
(참고) '~하여야 합니다.' 표현도 맞지만 '~해야 합니다.'로 짧게 사용하고 있습니다. 이후 문서 작성하실 때 참고하시면 좋을 것 같습니다. :)

2022-01-12 06:56 UTC, merged